# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20030 import InlineResponse20030  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20030(unittest.TestCase):
    """InlineResponse20030 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20030
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20030.InlineResponse20030()  # noqa: E501
        if include_optional :
            return InlineResponse20030(
                data = [
                    openapi_client.models.inline_response_200_30_data.inline_response_200_30_data(
                        date = '0', 
                        ticker = '0', 
                        signal_id = '0', 
                        signal_value = 56, )
                    ]
            )
        else :
            return InlineResponse20030(
                data = [
                    openapi_client.models.inline_response_200_30_data.inline_response_200_30_data(
                        date = '0', 
                        ticker = '0', 
                        signal_id = '0', 
                        signal_value = 56, )
                    ],
        )

    def testInlineResponse20030(self):
        """Test InlineResponse20030"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
