# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response2007_data_high_risk_companies import InlineResponse2007DataHighRiskCompanies  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse2007DataHighRiskCompanies(unittest.TestCase):
    """InlineResponse2007DataHighRiskCompanies unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2007DataHighRiskCompanies
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response2007_data_high_risk_companies.InlineResponse2007DataHighRiskCompanies()  # noqa: E501
        if include_optional :
            return InlineResponse2007DataHighRiskCompanies(
                company_name = '0', 
                lvl4_industry_name = '0', 
                overallrisk_change_12_w = 56, 
                overallrisk_value = 56
            )
        else :
            return InlineResponse2007DataHighRiskCompanies(
                company_name = '0',
                lvl4_industry_name = '0',
                overallrisk_change_12_w = 56,
                overallrisk_value = 56,
        )

    def testInlineResponse2007DataHighRiskCompanies(self):
        """Test InlineResponse2007DataHighRiskCompanies"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
