# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20024_data_spinsights_content import InlineResponse20024DataSpinsightsContent  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20024DataSpinsightsContent(unittest.TestCase):
    """InlineResponse20024DataSpinsightsContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20024DataSpinsightsContent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20024_data_spinsights_content.InlineResponse20024DataSpinsightsContent()  # noqa: E501
        if include_optional :
            return InlineResponse20024DataSpinsightsContent(
                spinsights_title = '0', 
                spinsights_asof_date = '0', 
                spindex_summary = '0', 
                final_article = '0', 
                final_topics = '0', 
                article_part1 = '0', 
                part1_topics = '0', 
                article_part2 = '0', 
                part2_topics = '0', 
                article_part3 = '0', 
                part3_topics = '0'
            )
        else :
            return InlineResponse20024DataSpinsightsContent(
                spinsights_title = '0',
                spinsights_asof_date = '0',
                spindex_summary = '0',
                final_article = '0',
                final_topics = '0',
                article_part1 = '0',
                part1_topics = '0',
                article_part2 = '0',
                part2_topics = '0',
                article_part3 = '0',
                part3_topics = '0',
        )

    def testInlineResponse20024DataSpinsightsContent(self):
        """Test InlineResponse20024DataSpinsightsContent"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
