# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import alphaiq_sdk
from alphaiq_sdk.models.inline_response20023 import InlineResponse20023  # noqa: E501
from alphaiq_sdk.rest import ApiException

class TestInlineResponse20023(unittest.TestCase):
    """InlineResponse20023 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20023
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = alphaiq_sdk.models.inline_response20023.InlineResponse20023()  # noqa: E501
        if include_optional :
            return InlineResponse20023(
                data = [
                    alphaiq_sdk.models.inline_response_200_23_data.inline_response_200_23_data(
                        date = '0', 
                        ticker = '0', 
                        signal_id = '0', 
                        signal_value = 56, )
                    ]
            )
        else :
            return InlineResponse20023(
                data = [
                    alphaiq_sdk.models.inline_response_200_23_data.inline_response_200_23_data(
                        date = '0', 
                        ticker = '0', 
                        signal_id = '0', 
                        signal_value = 56, )
                    ],
        )

    def testInlineResponse20023(self):
        """Test InlineResponse20023"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
