# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response2001_data import InlineResponse2001Data  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse2001Data(unittest.TestCase):
    """InlineResponse2001Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2001Data
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response2001_data.InlineResponse2001Data()  # noqa: E501
        if include_optional :
            return InlineResponse2001Data(
                token_type = '0', 
                refresh_token = '0', 
                id_token = '0', 
                access_token = '0'
            )
        else :
            return InlineResponse2001Data(
                token_type = '0',
                refresh_token = '0',
                id_token = '0',
                access_token = '0',
        )

    def testInlineResponse2001Data(self):
        """Test InlineResponse2001Data"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
