# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import alphaiq_sdk
from alphaiq_sdk.models.inline_response20012_data import InlineResponse20012Data  # noqa: E501
from alphaiq_sdk.rest import ApiException

class TestInlineResponse20012Data(unittest.TestCase):
    """InlineResponse20012Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20012Data
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = alphaiq_sdk.models.inline_response20012_data.InlineResponse20012Data()  # noqa: E501
        if include_optional :
            return InlineResponse20012Data(
                financials = [
                    alphaiq_sdk.models.inline_response_200_12_financials.inline_response_200_12_Financials(
                        banking = [
                            '0'
                            ], 
                        insurance = [
                            '0'
                            ], 
                        real_estate = [
                            '0'
                            ], )
                    ], 
                food = [
                    alphaiq_sdk.models.inline_response_200_12_food.inline_response_200_12_Food(
                        food_production = [
                            '0'
                            ], 
                        food_sales = [
                            '0'
                            ], )
                    ], 
                healthcare = [
                    alphaiq_sdk.models.inline_response_200_12_healthcare.inline_response_200_12_Healthcare(
                        consumer_healthcare = [
                            '0'
                            ], 
                        healthcare_industry = [
                            '0'
                            ], 
                        pharmaceuticals = [
                            '0'
                            ], )
                    ], 
                information = [
                    alphaiq_sdk.models.inline_response_200_12_information.inline_response_200_12_Information(
                        commercial_information_services = [
                            '0'
                            ], 
                        internet_services_and_websites = [
                            '0'
                            ], 
                        media_and_telecommunications = [
                            '0'
                            ], )
                    ], 
                energy = [
                    alphaiq_sdk.models.inline_response_200_12_energy.inline_response_200_12_Energy(
                        oil_and_gas = [
                            '0'
                            ], 
                        utilities = [
                            '0'
                            ], )
                    ], 
                industrials = [
                    alphaiq_sdk.models.inline_response_200_12_industrials.inline_response_200_12_Industrials(
                        industrial_components = [
                            '0'
                            ], 
                        industrial_equipment = [
                            '0'
                            ], 
                        industrial_materials = [
                            '0'
                            ], 
                        industrial_services = [
                            '0'
                            ], )
                    ], 
                information_tools = [
                    alphaiq_sdk.models.inline_response_200_12_information_tools.inline_response_200_12_Information_Tools(
                        integrated_circuits = [
                            '0'
                            ], 
                        it_hardware = [
                            '0'
                            ], 
                        software = [
                            '0'
                            ], )
                    ], 
                consumer_products_and_services = [
                    alphaiq_sdk.models.inline_response_200_12_consumer_products_and_services.inline_response_200_12_Consumer_Products_and_Services(
                        apparel_and_accessories = [
                            '0'
                            ], 
                        consumer_equipment_and_services = [
                            '0'
                            ], 
                        consumer_transportation_products_and_services = [
                            '0'
                            ], 
                        household_and_personal_care_products = [
                            '0'
                            ], )
                    ]
            )
        else :
            return InlineResponse20012Data(
        )

    def testInlineResponse20012Data(self):
        """Test InlineResponse20012Data"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
