# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.investment_researchers_api import InvestmentResearchersApi  # noqa: E501
from openapi_client.rest import ApiException


class TestInvestmentResearchersApi(unittest.TestCase):
    """InvestmentResearchersApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.investment_researchers_api.InvestmentResearchersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_gettoken_post(self):
        """Test case for auth_gettoken_post

        GetToken  # noqa: E501
        """
        pass

    def test_auth_refreshtoken_post(self):
        """Test case for auth_refreshtoken_post

        RefreshToken  # noqa: E501
        """
        pass

    def test_company_mapping_company_to_security_get(self):
        """Test case for company_mapping_company_to_security_get

        CompanyToSecurity  # noqa: E501
        """
        pass

    def test_company_spindex_get_latest_spindex_factors_get(self):
        """Test case for company_spindex_get_latest_spindex_factors_get

        GetLatestSpindexFactors  # noqa: E501
        """
        pass

    def test_company_spindex_get_latest_spindex_overall_risk_get(self):
        """Test case for company_spindex_get_latest_spindex_overall_risk_get

        GetLatestSpindexOverallRisk  # noqa: E501
        """
        pass

    def test_company_spindex_get_timeseries_spindex_factors_get(self):
        """Test case for company_spindex_get_timeseries_spindex_factors_get

        GetTimeseriesSpindexFactors  # noqa: E501
        """
        pass

    def test_company_spindex_get_timeseries_spindex_overall_risk_get(self):
        """Test case for company_spindex_get_timeseries_spindex_overall_risk_get

        GetTimeseriesSpindexOverallRisk  # noqa: E501
        """
        pass

    def test_factor_library_compass_questions_get(self):
        """Test case for factor_library_compass_questions_get

        GetCompassQuestions  # noqa: E501
        """
        pass

    def test_factor_library_spindex_factors_get(self):
        """Test case for factor_library_spindex_factors_get

        GetSpindexFactors  # noqa: E501
        """
        pass

    def test_generative_company_compass_report_content_ticker_get(self):
        """Test case for generative_company_compass_report_content_ticker_get

        GetCompassReportContent  # noqa: E501
        """
        pass

    def test_generative_company_question_answer_ticker_get(self):
        """Test case for generative_company_question_answer_ticker_get

        GetCompassExplorerQuestionAnswer  # noqa: E501
        """
        pass

    def test_generative_company_spinsights_explorer_ticker_get(self):
        """Test case for generative_company_spinsights_explorer_ticker_get

        GetSpinsightsExplorer  # noqa: E501
        """
        pass

    def test_generative_company_spinsights_report_content_ticker_get(self):
        """Test case for generative_company_spinsights_report_content_ticker_get

        GetSpinsightsReportContent  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
