# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import alphaiq_sdk
from alphaiq_sdk.models.inline_response20012_consumer_products_and_services import InlineResponse20012ConsumerProductsAndServices  # noqa: E501
from alphaiq_sdk.rest import ApiException

class TestInlineResponse20012ConsumerProductsAndServices(unittest.TestCase):
    """InlineResponse20012ConsumerProductsAndServices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20012ConsumerProductsAndServices
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = alphaiq_sdk.models.inline_response20012_consumer_products_and_services.InlineResponse20012ConsumerProductsAndServices()  # noqa: E501
        if include_optional :
            return InlineResponse20012ConsumerProductsAndServices(
                apparel_and_accessories = [
                    '0'
                    ], 
                consumer_equipment_and_services = [
                    '0'
                    ], 
                consumer_transportation_products_and_services = [
                    '0'
                    ], 
                household_and_personal_care_products = [
                    '0'
                    ]
            )
        else :
            return InlineResponse20012ConsumerProductsAndServices(
        )

    def testInlineResponse20012ConsumerProductsAndServices(self):
        """Test InlineResponse20012ConsumerProductsAndServices"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
