# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import alphaiq_sdk
from alphaiq_sdk.models.inline_response20022 import InlineResponse20022  # noqa: E501
from alphaiq_sdk.rest import ApiException

class TestInlineResponse20022(unittest.TestCase):
    """InlineResponse20022 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20022
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = alphaiq_sdk.models.inline_response20022.InlineResponse20022()  # noqa: E501
        if include_optional :
            return InlineResponse20022(
                data = [
                    alphaiq_sdk.models.inline_response_200_22_data.inline_response_200_22_data(
                        date = '0', 
                        ticker = '0', 
                        signal_id = '0', 
                        signal_value = 56, )
                    ]
            )
        else :
            return InlineResponse20022(
                data = [
                    alphaiq_sdk.models.inline_response_200_22_data.inline_response_200_22_data(
                        date = '0', 
                        ticker = '0', 
                        signal_id = '0', 
                        signal_value = 56, )
                    ],
        )

    def testInlineResponse20022(self):
        """Test InlineResponse20022"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
