# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20018_data import InlineResponse20018Data  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20018Data(unittest.TestCase):
    """InlineResponse20018Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20018Data
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20018_data.InlineResponse20018Data()  # noqa: E501
        if include_optional :
            return InlineResponse20018Data(
                chevron_corp___cvx = [
                    openapi_client.models.inline_response_200_18_data_chevron_corp___cvx_.inline_response_200_18_data_Chevron_Corp___CVX_(
                        date = '0', 
                        overallrisk = 56, )
                    ]
            )
        else :
            return InlineResponse20018Data(
                chevron_corp___cvx = [
                    openapi_client.models.inline_response_200_18_data_chevron_corp___cvx_.inline_response_200_18_data_Chevron_Corp___CVX_(
                        date = '0', 
                        overallrisk = 56, )
                    ],
        )

    def testInlineResponse20018Data(self):
        """Test InlineResponse20018Data"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
