# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import alphaiq_sdk
from alphaiq_sdk.api.investment_researchers_api import InvestmentResearchersApi  # noqa: E501
from alphaiq_sdk.rest import ApiException


class TestInvestmentResearchersApi(unittest.TestCase):
    """InvestmentResearchersApi unit test stubs"""

    def setUp(self):
        self.api = alphaiq_sdk.api.investment_researchers_api.InvestmentResearchersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_company_compass_report_ticker_get(self):
        """Test case for company_compass_report_ticker_get

        CompassReportPDF  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
