# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20028_data import InlineResponse20028Data  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20028Data(unittest.TestCase):
    """InlineResponse20028Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20028Data
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20028_data.InlineResponse20028Data()  # noqa: E501
        if include_optional :
            return InlineResponse20028Data(
                spindex_name = '0', 
                spindex_definition = '0'
            )
        else :
            return InlineResponse20028Data(
        )

    def testInlineResponse20028Data(self):
        """Test InlineResponse20028Data"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
