# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response2002_data_question_context import InlineResponse2002DataQuestionContext  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse2002DataQuestionContext(unittest.TestCase):
    """InlineResponse2002DataQuestionContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2002DataQuestionContext
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response2002_data_question_context.InlineResponse2002DataQuestionContext()  # noqa: E501
        if include_optional :
            return InlineResponse2002DataQuestionContext(
                id = 56, 
                text = '0', 
                document_id = '0', 
                document_section = '0', 
                document_type = '0', 
                document_date = '0', 
                document_link = '0'
            )
        else :
            return InlineResponse2002DataQuestionContext(
                id = 56,
                text = '0',
                document_id = '0',
                document_section = '0',
                document_type = '0',
                document_date = '0',
                document_link = '0',
        )

    def testInlineResponse2002DataQuestionContext(self):
        """Test InlineResponse2002DataQuestionContext"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
