# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import alphaiq_sdk
from alphaiq_sdk.models.inline_response2007 import InlineResponse2007  # noqa: E501
from alphaiq_sdk.rest import ApiException

class TestInlineResponse2007(unittest.TestCase):
    """InlineResponse2007 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2007
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = alphaiq_sdk.models.inline_response2007.InlineResponse2007()  # noqa: E501
        if include_optional :
            return InlineResponse2007(
                data = alphaiq_sdk.models.inline_response_200_7_data.inline_response_200_7_data(
                    as_of_date = '0', 
                    industry = '0', 
                    high_risk_companies = [
                        alphaiq_sdk.models.inline_response_200_7_data_high_risk_companies.inline_response_200_7_data_highRiskCompanies(
                            company_name = '0', 
                            lvl4_industry_name = '0', 
                            overallrisk_change_12_w = 56, 
                            overallrisk_value = 56, )
                        ], )
            )
        else :
            return InlineResponse2007(
                data = alphaiq_sdk.models.inline_response_200_7_data.inline_response_200_7_data(
                    as_of_date = '0', 
                    industry = '0', 
                    high_risk_companies = [
                        alphaiq_sdk.models.inline_response_200_7_data_high_risk_companies.inline_response_200_7_data_highRiskCompanies(
                            company_name = '0', 
                            lvl4_industry_name = '0', 
                            overallrisk_change_12_w = 56, 
                            overallrisk_value = 56, )
                        ], ),
        )

    def testInlineResponse2007(self):
        """Test InlineResponse2007"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
