# coding: utf-8

"""
    AlphaIQ API

    Quantitative Linguistics is the Future of Investment Research

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class GenerativeCompanyCompassReportContentModelCompassContent(BaseModel):
    """
    GenerativeCompanyCompassReportContentModelCompassContent
    """ # noqa: E501
    compass_title: StrictStr
    compass_asof_date: StrictStr
    executive_summary: StrictStr
    trending_up_article: StrictStr
    trending_up_topics: StrictStr
    popularity_article: StrictStr
    popularity_topics: StrictStr
    trending_down_article: StrictStr
    trending_down_topics: StrictStr
    __properties: ClassVar[List[str]] = ["compass_title", "compass_asof_date", "executive_summary", "trending_up_article", "trending_up_topics", "popularity_article", "popularity_topics", "trending_down_article", "trending_down_topics"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenerativeCompanyCompassReportContentModelCompassContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenerativeCompanyCompassReportContentModelCompassContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compass_title": obj.get("compass_title"),
            "compass_asof_date": obj.get("compass_asof_date"),
            "executive_summary": obj.get("executive_summary"),
            "trending_up_article": obj.get("trending_up_article"),
            "trending_up_topics": obj.get("trending_up_topics"),
            "popularity_article": obj.get("popularity_article"),
            "popularity_topics": obj.get("popularity_topics"),
            "trending_down_article": obj.get("trending_down_article"),
            "trending_down_topics": obj.get("trending_down_topics")
        })
        return _obj


