# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from alphaiq_sdk.configuration import Configuration


class InlineResponse20012Food(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'food_production': 'list[str]',
        'food_sales': 'list[str]'
    }

    attribute_map = {
        'food_production': 'Food Production',
        'food_sales': 'Food Sales'
    }

    def __init__(self, food_production=None, food_sales=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse20012Food - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._food_production = None
        self._food_sales = None
        self.discriminator = None

        if food_production is not None:
            self.food_production = food_production
        if food_sales is not None:
            self.food_sales = food_sales

    @property
    def food_production(self):
        """Gets the food_production of this InlineResponse20012Food.  # noqa: E501


        :return: The food_production of this InlineResponse20012Food.  # noqa: E501
        :rtype: list[str]
        """
        return self._food_production

    @food_production.setter
    def food_production(self, food_production):
        """Sets the food_production of this InlineResponse20012Food.


        :param food_production: The food_production of this InlineResponse20012Food.  # noqa: E501
        :type: list[str]
        """

        self._food_production = food_production

    @property
    def food_sales(self):
        """Gets the food_sales of this InlineResponse20012Food.  # noqa: E501


        :return: The food_sales of this InlineResponse20012Food.  # noqa: E501
        :rtype: list[str]
        """
        return self._food_sales

    @food_sales.setter
    def food_sales(self, food_sales):
        """Sets the food_sales of this InlineResponse20012Food.


        :param food_sales: The food_sales of this InlineResponse20012Food.  # noqa: E501
        :type: list[str]
        """

        self._food_sales = food_sales

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20012Food):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20012Food):
            return True

        return self.to_dict() != other.to_dict()
