# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from alphaiq_sdk.configuration import Configuration


class InlineResponse2002Data(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ticker': 'str',
        'company_name': 'str',
        'questions': 'list[InlineResponse2002DataQuestions]'
    }

    attribute_map = {
        'ticker': 'ticker',
        'company_name': 'company_name',
        'questions': 'questions'
    }

    def __init__(self, ticker=None, company_name=None, questions=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse2002Data - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ticker = None
        self._company_name = None
        self._questions = None
        self.discriminator = None

        self.ticker = ticker
        self.company_name = company_name
        self.questions = questions

    @property
    def ticker(self):
        """Gets the ticker of this InlineResponse2002Data.  # noqa: E501


        :return: The ticker of this InlineResponse2002Data.  # noqa: E501
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker):
        """Sets the ticker of this InlineResponse2002Data.


        :param ticker: The ticker of this InlineResponse2002Data.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and ticker is None:  # noqa: E501
            raise ValueError("Invalid value for `ticker`, must not be `None`")  # noqa: E501

        self._ticker = ticker

    @property
    def company_name(self):
        """Gets the company_name of this InlineResponse2002Data.  # noqa: E501


        :return: The company_name of this InlineResponse2002Data.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this InlineResponse2002Data.


        :param company_name: The company_name of this InlineResponse2002Data.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and company_name is None:  # noqa: E501
            raise ValueError("Invalid value for `company_name`, must not be `None`")  # noqa: E501

        self._company_name = company_name

    @property
    def questions(self):
        """Gets the questions of this InlineResponse2002Data.  # noqa: E501


        :return: The questions of this InlineResponse2002Data.  # noqa: E501
        :rtype: list[InlineResponse2002DataQuestions]
        """
        return self._questions

    @questions.setter
    def questions(self, questions):
        """Sets the questions of this InlineResponse2002Data.


        :param questions: The questions of this InlineResponse2002Data.  # noqa: E501
        :type: list[InlineResponse2002DataQuestions]
        """
        if self.local_vars_configuration.client_side_validation and questions is None:  # noqa: E501
            raise ValueError("Invalid value for `questions`, must not be `None`")  # noqa: E501

        self._questions = questions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2002Data):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2002Data):
            return True

        return self.to_dict() != other.to_dict()
