# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineResponse20026Data(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'question_answer': 'list[InlineResponse20026DataQuestionAnswer]'
    }

    attribute_map = {
        'question_answer': 'question_answer'
    }

    def __init__(self, question_answer=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse20026Data - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._question_answer = None
        self.discriminator = None

        self.question_answer = question_answer

    @property
    def question_answer(self):
        """Gets the question_answer of this InlineResponse20026Data.  # noqa: E501


        :return: The question_answer of this InlineResponse20026Data.  # noqa: E501
        :rtype: list[InlineResponse20026DataQuestionAnswer]
        """
        return self._question_answer

    @question_answer.setter
    def question_answer(self, question_answer):
        """Sets the question_answer of this InlineResponse20026Data.


        :param question_answer: The question_answer of this InlineResponse20026Data.  # noqa: E501
        :type: list[InlineResponse20026DataQuestionAnswer]
        """
        if self.local_vars_configuration.client_side_validation and question_answer is None:  # noqa: E501
            raise ValueError("Invalid value for `question_answer`, must not be `None`")  # noqa: E501

        self._question_answer = question_answer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20026Data):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20026Data):
            return True

        return self.to_dict() != other.to_dict()
