# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineResponse2003DataSpinsightsExplorer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'factor_name': 'str',
        'factor_description': 'str',
        'factor_summary': 'str'
    }

    attribute_map = {
        'id': 'id',
        'factor_name': 'factor_name',
        'factor_description': 'factor_description',
        'factor_summary': 'factor_summary'
    }

    def __init__(self, id=None, factor_name=None, factor_description=None, factor_summary=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse2003DataSpinsightsExplorer - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._factor_name = None
        self._factor_description = None
        self._factor_summary = None
        self.discriminator = None

        self.id = id
        self.factor_name = factor_name
        self.factor_description = factor_description
        self.factor_summary = factor_summary

    @property
    def id(self):
        """Gets the id of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501


        :return: The id of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2003DataSpinsightsExplorer.


        :param id: The id of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def factor_name(self):
        """Gets the factor_name of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501


        :return: The factor_name of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501
        :rtype: str
        """
        return self._factor_name

    @factor_name.setter
    def factor_name(self, factor_name):
        """Sets the factor_name of this InlineResponse2003DataSpinsightsExplorer.


        :param factor_name: The factor_name of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and factor_name is None:  # noqa: E501
            raise ValueError("Invalid value for `factor_name`, must not be `None`")  # noqa: E501

        self._factor_name = factor_name

    @property
    def factor_description(self):
        """Gets the factor_description of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501


        :return: The factor_description of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501
        :rtype: str
        """
        return self._factor_description

    @factor_description.setter
    def factor_description(self, factor_description):
        """Sets the factor_description of this InlineResponse2003DataSpinsightsExplorer.


        :param factor_description: The factor_description of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and factor_description is None:  # noqa: E501
            raise ValueError("Invalid value for `factor_description`, must not be `None`")  # noqa: E501

        self._factor_description = factor_description

    @property
    def factor_summary(self):
        """Gets the factor_summary of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501


        :return: The factor_summary of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501
        :rtype: str
        """
        return self._factor_summary

    @factor_summary.setter
    def factor_summary(self, factor_summary):
        """Sets the factor_summary of this InlineResponse2003DataSpinsightsExplorer.


        :param factor_summary: The factor_summary of this InlineResponse2003DataSpinsightsExplorer.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and factor_summary is None:  # noqa: E501
            raise ValueError("Invalid value for `factor_summary`, must not be `None`")  # noqa: E501

        self._factor_summary = factor_summary

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2003DataSpinsightsExplorer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2003DataSpinsightsExplorer):
            return True

        return self.to_dict() != other.to_dict()
