# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineResponse20012Energy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'oil_and_gas': 'list[str]',
        'utilities': 'list[str]'
    }

    attribute_map = {
        'oil_and_gas': 'Oil and Gas',
        'utilities': 'Utilities'
    }

    def __init__(self, oil_and_gas=None, utilities=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse20012Energy - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._oil_and_gas = None
        self._utilities = None
        self.discriminator = None

        if oil_and_gas is not None:
            self.oil_and_gas = oil_and_gas
        if utilities is not None:
            self.utilities = utilities

    @property
    def oil_and_gas(self):
        """Gets the oil_and_gas of this InlineResponse20012Energy.  # noqa: E501


        :return: The oil_and_gas of this InlineResponse20012Energy.  # noqa: E501
        :rtype: list[str]
        """
        return self._oil_and_gas

    @oil_and_gas.setter
    def oil_and_gas(self, oil_and_gas):
        """Sets the oil_and_gas of this InlineResponse20012Energy.


        :param oil_and_gas: The oil_and_gas of this InlineResponse20012Energy.  # noqa: E501
        :type: list[str]
        """

        self._oil_and_gas = oil_and_gas

    @property
    def utilities(self):
        """Gets the utilities of this InlineResponse20012Energy.  # noqa: E501


        :return: The utilities of this InlineResponse20012Energy.  # noqa: E501
        :rtype: list[str]
        """
        return self._utilities

    @utilities.setter
    def utilities(self, utilities):
        """Sets the utilities of this InlineResponse20012Energy.


        :param utilities: The utilities of this InlineResponse20012Energy.  # noqa: E501
        :type: list[str]
        """

        self._utilities = utilities

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20012Energy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20012Energy):
            return True

        return self.to_dict() != other.to_dict()
