# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineResponse20026DataQuestionAnswer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'question_text': 'str',
        'question_response': 'str'
    }

    attribute_map = {
        'id': 'id',
        'question_text': 'question_text',
        'question_response': 'question_response'
    }

    def __init__(self, id=None, question_text=None, question_response=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse20026DataQuestionAnswer - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._question_text = None
        self._question_response = None
        self.discriminator = None

        self.id = id
        self.question_text = question_text
        self.question_response = question_response

    @property
    def id(self):
        """Gets the id of this InlineResponse20026DataQuestionAnswer.  # noqa: E501


        :return: The id of this InlineResponse20026DataQuestionAnswer.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20026DataQuestionAnswer.


        :param id: The id of this InlineResponse20026DataQuestionAnswer.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def question_text(self):
        """Gets the question_text of this InlineResponse20026DataQuestionAnswer.  # noqa: E501


        :return: The question_text of this InlineResponse20026DataQuestionAnswer.  # noqa: E501
        :rtype: str
        """
        return self._question_text

    @question_text.setter
    def question_text(self, question_text):
        """Sets the question_text of this InlineResponse20026DataQuestionAnswer.


        :param question_text: The question_text of this InlineResponse20026DataQuestionAnswer.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and question_text is None:  # noqa: E501
            raise ValueError("Invalid value for `question_text`, must not be `None`")  # noqa: E501

        self._question_text = question_text

    @property
    def question_response(self):
        """Gets the question_response of this InlineResponse20026DataQuestionAnswer.  # noqa: E501


        :return: The question_response of this InlineResponse20026DataQuestionAnswer.  # noqa: E501
        :rtype: str
        """
        return self._question_response

    @question_response.setter
    def question_response(self, question_response):
        """Sets the question_response of this InlineResponse20026DataQuestionAnswer.


        :param question_response: The question_response of this InlineResponse20026DataQuestionAnswer.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and question_response is None:  # noqa: E501
            raise ValueError("Invalid value for `question_response`, must not be `None`")  # noqa: E501

        self._question_response = question_response

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20026DataQuestionAnswer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20026DataQuestionAnswer):
            return True

        return self.to_dict() != other.to_dict()
