# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineResponse20018Data(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'chevron_corp___cvx': 'list[InlineResponse20018DataChevronCorpCVX]'
    }

    attribute_map = {
        'chevron_corp___cvx': 'Chevron Corp. (CVX)'
    }

    def __init__(self, chevron_corp___cvx=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse20018Data - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._chevron_corp___cvx = None
        self.discriminator = None

        self.chevron_corp___cvx = chevron_corp___cvx

    @property
    def chevron_corp___cvx(self):
        """Gets the chevron_corp___cvx of this InlineResponse20018Data.  # noqa: E501


        :return: The chevron_corp___cvx of this InlineResponse20018Data.  # noqa: E501
        :rtype: list[InlineResponse20018DataChevronCorpCVX]
        """
        return self._chevron_corp___cvx

    @chevron_corp___cvx.setter
    def chevron_corp___cvx(self, chevron_corp___cvx):
        """Sets the chevron_corp___cvx of this InlineResponse20018Data.


        :param chevron_corp___cvx: The chevron_corp___cvx of this InlineResponse20018Data.  # noqa: E501
        :type: list[InlineResponse20018DataChevronCorpCVX]
        """
        if self.local_vars_configuration.client_side_validation and chevron_corp___cvx is None:  # noqa: E501
            raise ValueError("Invalid value for `chevron_corp___cvx`, must not be `None`")  # noqa: E501

        self._chevron_corp___cvx = chevron_corp___cvx

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20018Data):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20018Data):
            return True

        return self.to_dict() != other.to_dict()
