# coding: utf-8

"""
    AlphaIQ API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineResponse20012Financials(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'banking': 'list[str]',
        'insurance': 'list[str]',
        'real_estate': 'list[str]'
    }

    attribute_map = {
        'banking': 'Banking',
        'insurance': 'Insurance',
        'real_estate': 'Real Estate'
    }

    def __init__(self, banking=None, insurance=None, real_estate=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse20012Financials - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._banking = None
        self._insurance = None
        self._real_estate = None
        self.discriminator = None

        if banking is not None:
            self.banking = banking
        if insurance is not None:
            self.insurance = insurance
        if real_estate is not None:
            self.real_estate = real_estate

    @property
    def banking(self):
        """Gets the banking of this InlineResponse20012Financials.  # noqa: E501


        :return: The banking of this InlineResponse20012Financials.  # noqa: E501
        :rtype: list[str]
        """
        return self._banking

    @banking.setter
    def banking(self, banking):
        """Sets the banking of this InlineResponse20012Financials.


        :param banking: The banking of this InlineResponse20012Financials.  # noqa: E501
        :type: list[str]
        """

        self._banking = banking

    @property
    def insurance(self):
        """Gets the insurance of this InlineResponse20012Financials.  # noqa: E501


        :return: The insurance of this InlineResponse20012Financials.  # noqa: E501
        :rtype: list[str]
        """
        return self._insurance

    @insurance.setter
    def insurance(self, insurance):
        """Sets the insurance of this InlineResponse20012Financials.


        :param insurance: The insurance of this InlineResponse20012Financials.  # noqa: E501
        :type: list[str]
        """

        self._insurance = insurance

    @property
    def real_estate(self):
        """Gets the real_estate of this InlineResponse20012Financials.  # noqa: E501


        :return: The real_estate of this InlineResponse20012Financials.  # noqa: E501
        :rtype: list[str]
        """
        return self._real_estate

    @real_estate.setter
    def real_estate(self, real_estate):
        """Sets the real_estate of this InlineResponse20012Financials.


        :param real_estate: The real_estate of this InlineResponse20012Financials.  # noqa: E501
        :type: list[str]
        """

        self._real_estate = real_estate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20012Financials):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20012Financials):
            return True

        return self.to_dict() != other.to_dict()
